apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-inntekt-api
spec:
  replicas:
    min: 2
    max: 6
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 300m
      memory: 512Mi
