apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-inntekt-api
spec:
  env:
  - name: DATABASE_HOST
    value: b27dbvl009.preprod.local
  - name: DATABASE_NAME
    value: dp-inntekt-api-q2
  - name: KAFKA_SUBSUMSJON_BRUKT_DATA_TOPIC
    value: privat-dagpenger-subsumsjon-brukt-data-q2
  - name: HENTINNTEKTLISTE_URL
    value: "https://app-q2.adeo.no/inntektskomponenten-ws/rs/api/v1/hentinntektliste"

