# Example https://github.com/nais/naiserator/blob/master/examples/nais-max.yaml
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{image}}
  port: 8099
  webproxy: true
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/{{service_user}}
        mountPath: /var/run/secrets/nais.io/service_user
  secureLogs:
    enabled: true
  env:
    - name: DATABASE_HOST
      value: b27dbvl009.preprod.local
    - name: DATABASE_NAME
      value: dp-inntekt-db-q2
    - name: KAFKA_SUBSUMSJON_BRUKT_DATA_TOPIC
      value: "privat-dagpenger-subsumsjon-brukt-data-q2"
    - name: HENTINNTEKTLISTE_URL
      value: "https://app-q2.adeo.no/inntektskomponenten-ws/rs/api/v1/hentinntektliste"
    - name: APPLICATION_ID
      value: "dp-inntekt-api-consumer-q2"
    - name: ENHETSREGISTERET_URL
      value: "https://data.brreg.no/enhetsregisteret"