name: Deploy

on:
  status:
    branches:
      - feature/github-actions

jobs:
  create-deplyoment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Checkout event data
        run: cat ${GITHUB_EVENT_PATH}
      - name: Create deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_ACTOR} || true
